services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_USERNAME: "admin"
      DOCKER_INFLUXDB_INIT_PASSWORD: "adminadminadmin"
      DOCKER_INFLUXDB_INIT_ORG: "org1"
      DOCKER_INFLUXDB_INIT_BUCKET: "analytics"
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "super-token"
    volumes:
      - influxdb_data:/var/lib/influxdb2


  ekuiper:
    image: lfedge/ekuiper:1.12.0
    container_name: ekuiper
    ports:
      - "9081:9081"
    environment:
      MQTT_SOURCE__DEFAULT__SERVER: "tcp://mosquitto:1883"
    depends_on:
      - mosquitto
      - influxdb


  analytics-service:
    build: ./analytics-service
    container_name: analytics-service
    depends_on:
      - mosquitto
      - ekuiper
      - influxdb
      - notification-service
    environment:
      INFLUX_URL: http://influxdb:8086
      INFLUX_ORG: org1
      INFLUX_BUCKET: analytics
      INFLUX_TOKEN: super-token
      MQTT_BROKER: tcp://mosquitto:1883
      MQTT_EVENTS_TOPIC: iot/events
      NOTIF_GRPC_HOST: notification-service
      NOTIF_GRPC_PORT: 50051
      NOTIFICATION_HOST: notification-service
      NOTIFICATION_PORT: 50051

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "50051:50051"
      - "5000:5000"

volumes:
  influxdb_data:
